In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import glob
import folium
import requests
import json

In [2]:
df = pd.read_csv('datos/SESNSP/IDEFC_NM_ene24.csv', encoding = "ISO-8859-1")
df = df.fillna(value = 0)

In [3]:
df['Enero'] = df['Enero'].astype(float)

In [4]:
df = df.groupby(['Año', 'Clave_Ent', 'Entidad','Tipo de delito']).sum().reset_index()
df.drop(columns = ['Bien jurídico afectado','Subtipo de delito','Modalidad'], inplace = True)
df = df[df['Año'] < 2024]

In [5]:
df['Total_delitos'] = df.iloc[:, -12:].sum(axis=1)

In [6]:
df = df.drop(df.columns[4:16], axis=1)

In [7]:
df

Año  Clave_Ent         Entidad  \
0      2015          1  Aguascalientes   
1      2015          1  Aguascalientes   
2      2015          1  Aguascalientes   
3      2015          1  Aguascalientes   
4      2015          1  Aguascalientes   
...     ...        ...             ...   
11515  2023         32       Zacatecas   
11516  2023         32       Zacatecas   
11517  2023         32       Zacatecas   
11518  2023         32       Zacatecas   
11519  2023         32       Zacatecas   

                                          Tipo de delito  Total_delitos  
0                                                 Aborto            5.0  
1                                     Abuso de confianza          419.0  
2                                           Abuso sexual           18.0  
3                                           Acoso sexual            0.0  
4                                 Allanamiento de morada          169.0  
...                                                  ...            ...  
11515                                 Tráfico de menores            0.0  
11516                               Violación equiparada          129.0  
11517                                   Violación simple          161.0  
11518  Violencia de género en todas sus modalidades d...            0.0  
11519                                 Violencia familiar         3674.0  

[11520 rows x 5 columns]

# Anexar informacion adicional

In [8]:
df.groupby('Entidad')['Clave_Ent'].mean()

Entidad
Aguascalientes                      1.0
Baja California                     2.0
Baja California Sur                 3.0
Campeche                            4.0
Chiapas                             7.0
Chihuahua                           8.0
Ciudad de México                    9.0
Coahuila de Zaragoza                5.0
Colima                              6.0
Durango                            10.0
Guanajuato                         11.0
Guerrero                           12.0
Hidalgo                            13.0
Jalisco                            14.0
Michoacán de Ocampo                16.0
Morelos                            17.0
México                             15.0
Nayarit                            18.0
Nuevo León                         19.0
Oaxaca                             20.0
Puebla                             21.0
Querétaro                          22.0
Quintana Roo                       23.0
San Luis Potosí                    24.0
Sinaloa                         

In [9]:
df.sort_values('Entidad')['Entidad'].unique()

array(['Aguascalientes', 'Baja California', 'Baja California Sur',
       'Campeche', 'Chiapas', 'Chihuahua', 'Ciudad de México',
       'Coahuila de Zaragoza', 'Colima', 'Durango', 'Guanajuato',
       'Guerrero', 'Hidalgo', 'Jalisco', 'Michoacán de Ocampo', 'Morelos',
       'México', 'Nayarit', 'Nuevo León', 'Oaxaca', 'Puebla', 'Querétaro',
       'Quintana Roo', 'San Luis Potosí', 'Sinaloa', 'Sonora', 'Tabasco',
       'Tamaulipas', 'Tlaxcala', 'Veracruz de Ignacio de la Llave',
       'Yucatán', 'Zacatecas'], dtype=object)

### Agregando datos de poblacion

In [10]:
df_poblacion = pd.read_csv('datos/INEGI/Poblacion_01.csv')

In [11]:
df_poblacion

Entidad federativa      2010      2020
0                    Aguascalientes   1184996   1425607
1                   Baja California   3155070   3769020
2               Baja California Sur    637026    798447
3                          Campeche    822441    928363
4              Coahuila de Zaragoza   2748391   3146771
5                            Colima    650555    731391
6                           Chiapas   4796580   5543828
7                         Chihuahua   3406465   3741869
8                  Ciudad de México   8851080   9209944
9                           Durango   1632934   1832650
10                       Guanajuato   5486372   6166934
11                         Guerrero   3388768   3540685
12                          Hidalgo   2665018   3082841
13                          Jalisco   7350682   8348151
14                           México  15175862  16992418
15              Michoacán de Ocampo   4351037   4748846
16                          Morelos   1777227   1971520
17                          Nayarit   1084979   1235456
18                       Nuevo León   4653458   5784442
19                           Oaxaca   3801962   4132148
20                           Puebla   5779829   6583278
21                        Querétaro   1827937   2368467
22                     Quintana Roo   1325578   1857985
23                  San Luis Potosí   2585518   2822255
24                          Sinaloa   2767761   3026943
25                           Sonora   2662480   2944840
26                          Tabasco   2238603   2402598
27                       Tamaulipas   3268554   3527735
28                         Tlaxcala   1169936   1342977
29  Veracruz de Ignacio de la Llave   7643194   8062579
30                          Yucatán   1955577   2320898
31                        Zacatecas   1490668   1622138

In [12]:
#Realizar una interpolacion lineal para estimar la poblacion en los años faltantes
rango= [num for num in range(2011, 2024) if num != 2020]

for i in rango:
    df_poblacion[str(i)] = ((df_poblacion['2020']-df_poblacion['2010'])/10)*(i-2010) + df_poblacion['2010']

In [13]:
df_poblacion.sort_values('Entidad federativa', inplace=True)
df_poblacion.insert(1, 'Clave_Ent', list(range(1, 33)))

In [14]:
df_poblacion

Entidad federativa  Clave_Ent      2010      2020  \
0                    Aguascalientes          1   1184996   1425607   
1                   Baja California          2   3155070   3769020   
2               Baja California Sur          3    637026    798447   
3                          Campeche          4    822441    928363   
6                           Chiapas          5   4796580   5543828   
7                         Chihuahua          6   3406465   3741869   
8                  Ciudad de México          7   8851080   9209944   
4              Coahuila de Zaragoza          8   2748391   3146771   
5                            Colima          9    650555    731391   
9                           Durango         10   1632934   1832650   
10                       Guanajuato         11   5486372   6166934   
11                         Guerrero         12   3388768   3540685   
12                          Hidalgo         13   2665018   3082841   
13                          Jalisco         14   7350682   8348151   
15              Michoacán de Ocampo         15   4351037   4748846   
16                          Morelos         16   1777227   1971520   
14                           México         17  15175862  16992418   
17                          Nayarit         18   1084979   1235456   
18                       Nuevo León         19   4653458   5784442   
19                           Oaxaca         20   3801962   4132148   
20                           Puebla         21   5779829   6583278   
21                        Querétaro         22   1827937   2368467   
22                     Quintana Roo         23   1325578   1857985   
23                  San Luis Potosí         24   2585518   2822255   
24                          Sinaloa         25   2767761   3026943   
25                           Sonora         26   2662480   2944840   
26                          Tabasco         27   2238603   2402598   
27                       Tamaulipas         28   3268554   3527735   
28                         Tlaxcala         29   1169936   1342977   
29  Veracruz de Ignacio de la Llave         30   7643194   8062579   
30                          Yucatán         31   1955577   2320898   
31                        Zacatecas         32   1490668   1622138   

          2011        2012        2013        2014        2015        2016  \
0    1209057.1   1233118.2   1257179.3   1281240.4   1305301.5   1329362.6   
1    3216465.0   3277860.0   3339255.0   3400650.0   3462045.0   3523440.0   
2     653168.1    669310.2    685452.3    701594.4    717736.5    733878.6   
3     833033.2    843625.4    854217.6    864809.8    875402.0    885994.2   
6    4871304.8   4946029.6   5020754.4   5095479.2   5170204.0   5244928.8   
7    3440005.4   3473545.8   3507086.2   3540626.6   3574167.0   3607707.4   
8    8886966.4   8922852.8   8958739.2   8994625.6   9030512.0   9066398.4   
4    2788229.0   2828067.0   2867905.0   2907743.0   2947581.0   2987419.0   
5     658638.6    666722.2    674805.8    682889.4    690973.0    699056.6   
9    1652905.6   1672877.2   1692848.8   1712820.4   1732792.0   1752763.6   
10   5554428.2   5622484.4   5690540.6   5758596.8   5826653.0   5894709.2   
11   3403959.7   3419151.4   3434343.1   3449534.8   3464726.5   3479918.2   
12   2706800.3   2748582.6   2790364.9   2832147.2   2873929.5   2915711.8   
13   7450428.9   7550175.8   7649922.7   7749669.6   7849416.5   7949163.4   
15   4390817.9   4430598.8   4470379.7   4510160.6   4549941.5   4589722.4   
16   1796656.3   1816085.6   1835514.9   1854944.2   1874373.5   1893802.8   
14  15357517.6  15539173.2  15720828.8  15902484.4  16084140.0  16265795.6   
17   1100026.7   1115074.4   1130122.1   1145169.8   1160217.5   1175265.2   
18   4766556.4   4879654.8   4992753.2   5105851.6   5218950.0   5332048.4   
19   3834980.6   3867999.2   3901017.8   3934036.4   3967055.0   4000073.6   
20   5860173.9   5940518.8   6020863.7   6101208.6   6181553.5   626

In [15]:
df_poblacion = df_poblacion.loc[:,'2010':].stack()

In [16]:
df_poblacion = df_poblacion.reset_index()
df_poblacion = df_poblacion.rename(columns={'level_0': 'Clave_Ent', 'level_1': 'Año', 0: 'Poblacion'})
df_poblacion['Clave_Ent'] += 1

In [17]:
df_poblacion

Clave_Ent   Año  Poblacion
0            1  2010  1184996.0
1            1  2020  1425607.0
2            1  2011  1209057.1
3            1  2012  1233118.2
4            1  2013  1257179.3
..         ...   ...        ...
443         32  2018  1595844.0
444         32  2019  1608991.0
445         32  2021  1635285.0
446         32  2022  1648432.0
447         32  2023  1661579.0

[448 rows x 3 columns]

In [18]:
df_poblacion['Año'] = df_poblacion['Año'].astype(int)

In [19]:
df_poblacion.dtypes

Clave_Ent      int64
Año            int32
Poblacion    float64
dtype: object

In [20]:
df = pd.merge(df, df_poblacion, on=['Clave_Ent', 'Año'], how='inner')

In [21]:
df

Año  Clave_Ent         Entidad  \
0      2015          1  Aguascalientes   
1      2015          1  Aguascalientes   
2      2015          1  Aguascalientes   
3      2015          1  Aguascalientes   
4      2015          1  Aguascalientes   
...     ...        ...             ...   
11515  2023         32       Zacatecas   
11516  2023         32       Zacatecas   
11517  2023         32       Zacatecas   
11518  2023         32       Zacatecas   
11519  2023         32       Zacatecas   

                                          Tipo de delito  Total_delitos  \
0                                                 Aborto            5.0   
1                                     Abuso de confianza          419.0   
2                                           Abuso sexual           18.0   
3                                           Acoso sexual            0.0   
4                                 Allanamiento de morada          169.0   
...                                                  ...            ...   
11515                                 Tráfico de menores            0.0   
11516                               Violación equiparada          129.0   
11517                                   Violación simple          161.0   
11518  Violencia de género en todas sus modalidades d...            0.0   
11519                                 Violencia familiar         3674.0   

       Poblacion  
0      1305301.5  
1      1305301.5  
2      1305301.5  
3      1305301.5  
4      1305301.5  
...          ...  
11515  1661579.0  
11516  1661579.0  
11517  1661579.0  
11518  1661579.0  
11519  1661579.0  

[11520 rows x 6 columns]

### Agregando datos de PIB

In [22]:
df_pib = pd.read_csv('datos/INEGI/PIBE_r_1.csv')
df_pib['2023'] = df_pib.iloc[:, -8:].mean(axis=1)
df_pib = df_pib.drop(df_pib.loc[:,'1980':'2014'], axis=1)

In [23]:
df_pib.sort_values('Concepto', inplace=True)
df_pib.insert(1, 'Clave_Ent', list(range(1, 33)))

In [24]:
df_pib

Concepto  Clave_Ent     2015  \
0                                   Aguascalientes          1   294497   
1                                  Baja California          2   795081   
2                              Baja California Sur          3   156072   
3                                         Campeche          4   700311   
6                                          Chiapas          5   364001   
7                                        Chihuahua          6   803883   
8                                 Ciudad de México          7  3503520   
4                             Coahuila de Zaragoza          8   897702   
5                                           Colima          9   141029   
9                                          Durango         10   300289   
10                                      Guanajuato         11  1026150   
11                                        Guerrero         12   314104   
12                                         Hidalgo         13   413909   
13                                         Jalisco         14  1626751   
15                             Michoacán de Ocampo         15   573506   
16                                         Morelos         16   265751   
14                                          México         17  2007572   
17                                         Nayarit         18   147429   
18                                      Nuevo León         19  1728164   
19                                          Oaxaca         20   401404   
20                                          Puebla         21   765650   
21                                       Querétaro         22   574578   
22                                    Quintana Roo         23   318608   
23                                 San Luis Potosí         24   480025   
24                                         Sinaloa         25   485181   
25                                          Sonora         26   760031   
26                                         Tabasco         27   553280   
27                                      Tamaulipas         28   712997   
28                                        Tlaxcala         29   137054   
29                 Veracruz de Ignacio de la Llave         30  1082922   
30                                         Yucatán         31   322098   
31                                       Zacatecas         32   214605   

       2016     2017     2018     2019     2020     2021     2022         2023  
0    307396   314242   327926   327058   303556   312954   316500   313016.125  
1    828692   863601   878817   897460   833361   901664   929459   866016.875  
2    163095   170784   184618   179624   152597   170695   177421   169363.250  
3    663239   595667   564591   544914   502567   491694   473101   567010.500  
6    369919   359734   353600   349375   334057   349531   368789   356125.750  
7    830489   851284   853323   862012   809562   849224   919617   847424.250  
8   3571368  3646318  3694575  3688277  3292782  3480722  3640388  3564743.750  
4    901719   941582   966055   974554   862347   916340   922287   922823.250  
5    140705   150360   153808   161221   148214   147102   148130   148821.125  
9    305382   304647   308981   308659   283133   299795   296963   300981.125  
10  1064743  1115371  1120603  1101227  1023965  1094692  1128686  1084429.625  
11   313422   308568   317845   315286   288104   299520   306831   307960.000  
12   418466   416409   418630   405465   360341   384460   426819   405562.375  
13  1676419  1708140  1754180  1768025  1611603  1693743  1783505  1702795.750  
15   591410   610394   633757   636103   600472   623966   646901   614563.625  
16   274365   277403   273245   267471   241212   255737   256740   263990.500  
14  2058753  2166132  2243798  2189632  2011109  2125071  2184863  2123366.250  
17   152586   155110   155758   158044   142684   155442   161869   153615.250  
18  1743961  1809344  1909026  1944221  1754968  1880258  19

In [25]:
df_pib = df_pib.loc[:,'2015':].stack()

In [26]:
df_pib = df_pib.reset_index()
df_pib = df_pib.rename(columns={'level_0': 'Clave_Ent', 'level_1': 'Año', 0: 'PIB'})
df_pib['Clave_Ent'] += 1

In [27]:
df_pib

Clave_Ent   Año       PIB
0            1  2015  294497.0
1            1  2016  307396.0
2            1  2017  314242.0
3            1  2018  327926.0
4            1  2019  327058.0
..         ...   ...       ...
283         32  2019  219945.0
284         32  2020  210123.0
285         32  2021  219774.0
286         32  2022  221026.0
287         32  2023  218885.5

[288 rows x 3 columns]

In [28]:
df_pib['Año'] = df_pib['Año'].astype(int)

In [29]:
df = pd.merge(df, df_pib, on=['Clave_Ent', 'Año'], how='inner')

In [30]:
df

Año  Clave_Ent         Entidad  \
0      2015          1  Aguascalientes   
1      2015          1  Aguascalientes   
2      2015          1  Aguascalientes   
3      2015          1  Aguascalientes   
4      2015          1  Aguascalientes   
...     ...        ...             ...   
11515  2023         32       Zacatecas   
11516  2023         32       Zacatecas   
11517  2023         32       Zacatecas   
11518  2023         32       Zacatecas   
11519  2023         32       Zacatecas   

                                          Tipo de delito  Total_delitos  \
0                                                 Aborto            5.0   
1                                     Abuso de confianza          419.0   
2                                           Abuso sexual           18.0   
3                                           Acoso sexual            0.0   
4                                 Allanamiento de morada          169.0   
...                                                  ...            ...   
11515                                 Tráfico de menores            0.0   
11516                               Violación equiparada          129.0   
11517                                   Violación simple          161.0   
11518  Violencia de género en todas sus modalidades d...            0.0   
11519                                 Violencia familiar         3674.0   

       Poblacion       PIB  
0      1305301.5  294497.0  
1      1305301.5  294497.0  
2      1305301.5  294497.0  
3      1305301.5  294497.0  
4      1305301.5  294497.0  
...          ...       ...  
11515  1661579.0  218885.5  
11516  1661579.0  218885.5  
11517  1661579.0  218885.5  
11518  1661579.0  218885.5  
11519  1661579.0  218885.5  

[11520 rows x 7 columns]

### Agregando datos de tasa de desocupacion

In [31]:
df_desoc = pd.read_csv('datos/INEGi/TasaDesocupacion.CSV')
df_desoc = df_desoc[df_desoc['Indicador'] == 'Total']
df_desoc = df_desoc.drop('Indicador', axis=1)
df_desoc = df_desoc.reset_index().drop('index', axis=1)

In [32]:
df_desoc.loc[:,'2019/01':]

2019/01  2019/02  2019/03  2019/04  2020/01  2020/02   2020/03  2020/04  \
0   3.28535  3.67106  3.79282  3.34141  3.35009      NaN   5.19230  5.19754   
1   2.51192  2.55760  2.89908  2.21851  2.16798      NaN   2.74817  2.88007   
2   3.95454  4.61803  4.94592  4.37215  3.83703      NaN   7.38778  5.42497   
3   3.47572  3.47649  3.00970  3.22312  2.78253      NaN   3.82608  3.38969   
4   4.24849  4.88419  4.81236  4.27631  4.76719      NaN   7.37167  6.15794   
5   3.91841  3.62257  3.81958  2.95786  3.12872      NaN   4.14453  3.80916   
6   3.09453  3.60047  3.70345  2.45755  2.58386      NaN   3.39902  2.72578   
7   3.03526  3.38451  3.19745  2.57083  3.49114      NaN   4.69780  3.73507   
8   4.73037  5.15945  4.99577  5.10120  4.72524      NaN   7.99090  6.63142   
9   4.64486  4.25457  3.94023  3.25998  4.05512      NaN   4.80873  4.87685   
10  3.98003  3.76565  3.80883  3.29813  3.55997      NaN   6.64331  5.33650   
11  1.82428  1.39868  1.40250  1.45060  1.58399      NaN   3.28630  2.40477   
12  2.47825  2.69448  2.05468  2.50749  1.86791      NaN   3.33658  2.19263   
13  2.58847  2.96334  3.18748  3.05405  2.93746      NaN   5.00079  4.05613   
14  4.19468  4.50421  4.73925  4.55548  5.22709      NaN   6.56510  6.39335   
15  2.32427  2.92664  2.92755  2.70983  2.34420      NaN   2.55683  2.29159   
16  1.78594  2.34311  2.68176  2.42082  1.94706      NaN   2.72547  2.42373   
17  3.65747  3.96553  4.48981  3.56766  3.71128      NaN   5.21592  4.03884   
18  3.40065  3.49868  3.61190  3.72879  3.74490      NaN   5.25984  4.22835   
19  1.79996  1.29433  2.02435  2.01734  1.70744      NaN   3.05912  1.69948   
20  2.41344  2.75398  2.89198  2.49711  2.80175      NaN   4.67189  6.00336   
21  2.64342  4.53436  5.35413  4.71727  3.49576      NaN   8.21835  6.91009   
22  2.95590  2.73219  3.55064  3.08040  2.96336      NaN  10.17038  8.57636   
23  2.17682  2.86328  3.30765  2.28111  2.07787      NaN   3.98296  3.26546   
24  3.49490  2.99788  3.63153  2.84503  2.88295      NaN   5.28873  2.42905   
25  4.25036  4.16152  4.94885  3.78906  4.37054      NaN   6.68780  4.94429   
26  7.51282  7.24434  7.17210  6.37283  5.26961      NaN   7.45122  7.96063   
27  3.68976  3.37267  3.59923  3.21892  3.18924      NaN   3.78681  3.29395   
28  3.79335  3.99275  3.62364  3.54575  4.02238      NaN   6.42156  5.58101   
29  2.83521  2.56691  3.54736  2.85788  2.68437      NaN   2.75096  3.36439   
30  1.90910  1.78375  1.96690  1.91823  1.97608      NaN   3.56538  2.67472   
31  3.18193  3.20892  3.32843  2.52846  3.32469      NaN   3.89741  4.16117   

    2021/01  2021/02  2021/03  2021/04  2022/01  2022/02  2022/03  2022/04  \
0   3.62242  3.87156  4.62574  4.37726  3.51969  3.76820  4.03923  3.76756   
1   2.55476  2.44667  2.87954  2.04351  1.91049  2.50984  2.59254  2.70224   
2   4.98176  4.40950  4.25482  2.59220  2.87475  2.73295  2.86790  2.85079   
3   2.92643  2.89527  3.05700  2.95580  3.06809  2.95330  2.29772  1.97641   
4   5.11096  4.84208  4.93013  4.80892  5.02271  4.02557  4.24342  3.41466   
5   3.20564  3.19790  2.91652  3.12393  2.77123  2.56226  2.60985  2.35763   
6   3.17416  2.90871  3.28256  3.33131  2.49952  2.58906  2.28847  2.32698   
7   3.97549  3.61242  3.02856  2.86673  2.59984  2.45553  2.46536  1.98906   
8   7.30910  7.25668  6.99109  5.89173  5.84765  5.39836  5.25200  4.53060   
9   4.14994  4.59470  4.21080  3.43068  3.57521  3.26514  3.25675  3.08720   
10  5.91211  5.60891  5.41382  3.91123  3.63624  2.93240  4.01364  3.07080   
11  1.69174  1.50949  1.59391  1.41565  1.60378  1.48935  1.71875  0.80639   
12  4.02292  2.22535  2.87668  2.70085  2.22827  2.64529  2.30357  2.20085   
13  3.71942  3.34635  3.38636  3.09968  2.36197  2.34432  2.81465  2.36228   
14  6.50941  6.21840  5.82300  4.65943  5.32569  4.21645  4.83120  4.46142   
15  2.54275  1.98448  2.19764  2.54180  1.62119  1.72564  1.85106  1.66851   
16  2.00878  2.55837  2.45704  2.38563  1.85844  2.12956  2.39593  2.7

In [33]:
df_desoc = df_desoc.fillna(method = 'ffill', axis=1)

In [34]:
df_desoc.loc[:,'2019/01':]

2019/01  2019/02  2019/03  2019/04  2020/01  2020/02   2020/03  2020/04  \
0   3.28535  3.67106  3.79282  3.34141  3.35009  3.35009    5.1923  5.19754   
1   2.51192   2.5576  2.89908  2.21851  2.16798  2.16798   2.74817  2.88007   
2   3.95454  4.61803  4.94592  4.37215  3.83703  3.83703   7.38778  5.42497   
3   3.47572  3.47649   3.0097  3.22312  2.78253  2.78253   3.82608  3.38969   
4   4.24849  4.88419  4.81236  4.27631  4.76719  4.76719   7.37167  6.15794   
5   3.91841  3.62257  3.81958  2.95786  3.12872  3.12872   4.14453  3.80916   
6   3.09453  3.60047  3.70345  2.45755  2.58386  2.58386   3.39902  2.72578   
7   3.03526  3.38451  3.19745  2.57083  3.49114  3.49114    4.6978  3.73507   
8   4.73037  5.15945  4.99577   5.1012  4.72524  4.72524    7.9909  6.63142   
9   4.64486  4.25457  3.94023  3.25998  4.05512  4.05512   4.80873  4.87685   
10  3.98003  3.76565  3.80883  3.29813  3.55997  3.55997   6.64331   5.3365   
11  1.82428  1.39868   1.4025   1.4506  1.58399  1.58399    3.2863  2.40477   
12  2.47825  2.69448  2.05468  2.50749  1.86791  1.86791   3.33658  2.19263   
13  2.58847  2.96334  3.18748  3.05405  2.93746  2.93746   5.00079  4.05613   
14  4.19468  4.50421  4.73925  4.55548  5.22709  5.22709    6.5651  6.39335   
15  2.32427  2.92664  2.92755  2.70983   2.3442   2.3442   2.55683  2.29159   
16  1.78594  2.34311  2.68176  2.42082  1.94706  1.94706   2.72547  2.42373   
17  3.65747  3.96553  4.48981  3.56766  3.71128  3.71128   5.21592  4.03884   
18  3.40065  3.49868   3.6119  3.72879   3.7449   3.7449   5.25984  4.22835   
19  1.79996  1.29433  2.02435  2.01734  1.70744  1.70744   3.05912  1.69948   
20  2.41344  2.75398  2.89198  2.49711  2.80175  2.80175   4.67189  6.00336   
21  2.64342  4.53436  5.35413  4.71727  3.49576  3.49576   8.21835  6.91009   
22   2.9559  2.73219  3.55064   3.0804  2.96336  2.96336  10.17038  8.57636   
23  2.17682  2.86328  3.30765  2.28111  2.07787  2.07787   3.98296  3.26546   
24   3.4949  2.99788  3.63153  2.84503  2.88295  2.88295   5.28873  2.42905   
25  4.25036  4.16152  4.94885  3.78906  4.37054  4.37054    6.6878  4.94429   
26  7.51282  7.24434   7.1721  6.37283  5.26961  5.26961   7.45122  7.96063   
27  3.68976  3.37267  3.59923  3.21892  3.18924  3.18924   3.78681  3.29395   
28  3.79335  3.99275  3.62364  3.54575  4.02238  4.02238   6.42156  5.58101   
29  2.83521  2.56691  3.54736  2.85788  2.68437  2.68437   2.75096  3.36439   
30   1.9091  1.78375   1.9669  1.91823  1.97608  1.97608   3.56538  2.67472   
31  3.18193  3.20892  3.32843  2.52846  3.32469  3.32469   3.89741  4.16117   

    2021/01  2021/02  2021/03  2021/04  2022/01  2022/02  2022/03  2022/04  \
0   3.62242  3.87156  4.62574  4.37726  3.51969   3.7682  4.03923  3.76756   
1   2.55476  2.44667  2.87954  2.04351  1.91049  2.50984  2.59254  2.70224   
2   4.98176   4.4095  4.25482   2.5922  2.87475  2.73295   2.8679  2.85079   
3   2.92643  2.89527    3.057   2.9558  3.06809   2.9533  2.29772  1.97641   
4   5.11096  4.84208  4.93013  4.80892  5.02271  4.02557  4.24342  3.41466   
5   3.20564   3.1979  2.91652  3.12393  2.77123  2.56226  2.60985  2.35763   
6   3.17416  2.90871  3.28256  3.33131  2.49952  2.58906  2.28847  2.32698   
7   3.97549  3.61242  3.02856  2.86673  2.59984  2.45553  2.46536  1.98906   
8    7.3091  7.25668  6.99109  5.89173  5.84765  5.39836    5.252   4.5306   
9   4.14994   4.5947   4.2108  3.43068  3.57521  3.26514  3.25675   3.0872   
10  5.91211  5.60891  5.41382  3.91123  3.63624   2.9324  4.01364   3.0708   
11  1.69174  1.50949  1.59391  1.41565  1.60378  1.48935  1.71875  0.80639   
12  4.02292  2.22535  2.87668  2.70085  2.22827  2.64529  2.30357  2.20085   
13  3.71942  3.34635  3.38636  3.09968  2.36197  2.34432  2.81465  2.36228   
14  6.50941   6.2184    5.823  4.65943  5.32569  4.21645   4.8312  4.46142   
15  2.54275  1.98448  2.19764   2.5418  1.62119  1.72564  1.85106  1.66851   
16  2.00878  2.55837  2.45704  2.38563  1.85844  2.12956  2.39593  2.7

In [35]:
for i in range(1,10):
    year = 2024-i
    df_desoc.insert(1, str(year), df_desoc.iloc[:,-4:].mean(axis=1))
    df_desoc.drop(df_desoc.iloc[:,-4:], axis=1, inplace=True)

In [36]:
df_desoc.sort_values('Entidad federativa', inplace=True)
df_desoc.insert(1, 'Clave_Ent', list(range(1, 33)))

In [37]:
df_desoc

Entidad federativa  Clave_Ent      2015      2016      2017  \
0                    Aguascalientes          1  4.503325  3.972855  3.630322   
1                   Baja California          2   4.16816  2.688038  2.852475   
2               Baja California Sur          3  4.786112   4.60931   4.35683   
3                          Campeche          4  2.884725  3.702132  3.803275   
6                           Chiapas          5  3.093762  3.062107  2.574955   
7                         Chihuahua          6  3.728603  3.158615   2.70045   
8                  Ciudad de México          7  5.344278   5.03398  4.602907   
4              Coahuila de Zaragoza          8  5.101025  4.449495  4.388165   
5                            Colima          9  4.677623  4.083425   3.62567   
9                           Durango         10  4.901497  4.492987  3.818468   
10                       Guanajuato         11  4.743203  3.994552  3.573695   
11                         Guerrero         12  2.092598  2.018405   1.64664   
12                          Hidalgo         13  3.820935  3.144935  2.894388   
13                          Jalisco         14  4.683198  3.644837  2.820418   
15              Michoacán de Ocampo         15   3.17132  2.759867  2.607193   
16                          Morelos         16  3.256405   2.63523  2.066987   
14                           México         17  5.435442  5.130045  3.992805   
17                          Nayarit         18   5.38059   3.98708   3.57958   
18                       Nuevo León         19  4.601533  4.283525  3.797108   
19                           Oaxaca         20  2.948622  1.961298  2.188868   
20                           Puebla         21  3.206615   2.94541  2.747705   
21                        Querétaro         22  4.719215  4.440607  4.318507   
22                     Quintana Roo         23   4.01441   3.26419  3.171453   
23                  San Luis Potosí         24  3.000545  2.490568  2.384958   
24                          Sinaloa         25  4.320807  3.760178  3.664942   
25                           Sonora         26  4.911008   5.01059  3.761058   
26                          Tabasco         27  6.741325  7.451835  6.995642   
27                       Tamaulipas         28   4.84393  4.688382  4.174792   
28                         Tlaxcala         29  4.876298  4.121733  3.735158   
29  Veracruz de Ignacio de la Llave         30  3.713097  3.549348   3.53469   
30                          Yucatán         31  2.612868  1.991802   2.05953   
31                        Zacatecas         32   3.60198  2.864565  2.788855   

        2018      2019      2020      2021      2022      2023  
0     3.4501   3.52266  4.272505  4.124245   3.77367  3.225192  
1    2.51368  2.546778   2.49105   2.48112  2.428777  2.175982  
2   3.782522   4.47266  5.121702   4.05957  2.831597   2.72739  
3    3.26537  3.296257  3.195207  2.958625   2.57388   1.76395  
6    2.78294     3.214   2.82313  3.174185  2.426007  2.135168  
7   3.153355  3.047013  3.853788    3.3708  2.377448  2.501935  
8    4.61948  4.996697    6.0182   6.86215  5.257153   4.02441  
4    4.14186  4.555338  5.765998  4.923023   4.17659   3.88704  
5   3.252147  3.579605  3.552782  3.110997  2.575242  2.301085  
9   4.290887   4.02491  4.448955   4.09653  3.296075  2.944163  
10  3.597023   3.71316  4.774938  5.211518   3.41327   3.13524  
11  1.214045  1.519015  2.214762  1.552698  1.404568  1.165725  
12  2.500802  2.433725  2.316257   2.95645  2.344495  2.421037  
13  2.713778  2.948335   3.73296  3.387952  2.470805  2.442933  
15  2.215203  2.722072  2.384205  2.316667    1.7166  1.928385  
16  2.119633  2.307907   2.26083  2.352455  2.277493  1.861417  
14   3.95119  4.498405  5.853158   5.80256   4.70869  3.642895  
17  3.948088  3.920117   4.16933   2.86289  2.642165    2.1028  
18  3.588407  3.560005  4.244497   4.48505  3.884353  3.100123  
19  1.573372  1.783995   2.04337  1.601913  1.426865  1.512328  
20  2.54975

In [38]:
df_desoc = df_desoc.loc[:,'2015':].stack()

In [39]:
df_desoc = df_desoc.reset_index()
df_desoc = df_desoc.rename(columns={'level_0': 'Clave_Ent', 'level_1': 'Año', 0: 'Desocupacion'})
df_desoc['Clave_Ent'] += 1

In [40]:
df_desoc

Clave_Ent   Año Desocupacion
0            1  2015     4.503325
1            1  2016     3.972855
2            1  2017     3.630322
3            1  2018       3.4501
4            1  2019      3.52266
..         ...   ...          ...
283         32  2019     3.061935
284         32  2020      3.67699
285         32  2021     3.504418
286         32  2022     2.797048
287         32  2023     2.872008

[288 rows x 3 columns]

In [41]:
df_desoc['Año'] = df_desoc['Año'].astype(int)

In [42]:
df = pd.merge(df, df_desoc, on=['Clave_Ent', 'Año'], how='inner')

In [43]:
df

Año  Clave_Ent         Entidad  \
0      2015          1  Aguascalientes   
1      2015          1  Aguascalientes   
2      2015          1  Aguascalientes   
3      2015          1  Aguascalientes   
4      2015          1  Aguascalientes   
...     ...        ...             ...   
11515  2023         32       Zacatecas   
11516  2023         32       Zacatecas   
11517  2023         32       Zacatecas   
11518  2023         32       Zacatecas   
11519  2023         32       Zacatecas   

                                          Tipo de delito  Total_delitos  \
0                                                 Aborto            5.0   
1                                     Abuso de confianza          419.0   
2                                           Abuso sexual           18.0   
3                                           Acoso sexual            0.0   
4                                 Allanamiento de morada          169.0   
...                                                  ...            ...   
11515                                 Tráfico de menores            0.0   
11516                               Violación equiparada          129.0   
11517                                   Violación simple          161.0   
11518  Violencia de género en todas sus modalidades d...            0.0   
11519                                 Violencia familiar         3674.0   

       Poblacion       PIB Desocupacion  
0      1305301.5  294497.0     4.503325  
1      1305301.5  294497.0     4.503325  
2      1305301.5  294497.0     4.503325  
3      1305301.5  294497.0     4.503325  
4      1305301.5  294497.0     4.503325  
...          ...       ...          ...  
11515  1661579.0  218885.5     2.872008  
11516  1661579.0  218885.5     2.872008  
11517  1661579.0  218885.5     2.872008  
11518  1661579.0  218885.5     2.872008  
11519  1661579.0  218885.5     2.872008  

[11520 rows x 8 columns]

### Agregando datos de Eficiencia terminal de la enseñanza primaria

In [44]:
df_efic = pd.read_csv('datos/INEGI/EficienciaTerminal.csv')

In [45]:
df_efic

Entidad federativa       2015       2016       2017  \
0                    Aguascalientes   99.48262   99.35626  100.07392   
1                   Baja California   98.14218   98.66109   97.24271   
2               Baja California Sur  100.85804  100.22020  101.06473   
3                          Campeche   97.12600   95.57463   95.45344   
4              Coahuila de Zaragoza   98.00489   98.33659   99.06695   
5                            Colima  104.72692   98.76622   97.61600   
6                           Chiapas   95.16524   94.79580   94.79650   
7                         Chihuahua   97.12574   99.88062   97.52694   
8                  Ciudad de México   98.97006   96.48690   97.40903   
9                           Durango   98.18177   96.03335   95.33467   
10                       Guanajuato   98.85114   96.92807   96.81603   
11                         Guerrero   97.02454   97.46167   93.85728   
12                          Hidalgo  102.89174  102.91048  101.53272   
13                          Jalisco   96.40105   95.46034   96.37977   
14                           México   99.41544   99.41464   98.47468   
15              Michoacán de Ocampo   94.29299   95.71484   95.53016   
16                          Morelos   96.52155   95.99525   95.84663   
17                          Nayarit  100.89731   99.37761   99.21260   
18                       Nuevo León  101.67270  103.10297  102.89772   
19                           Oaxaca   91.30149   88.39060   96.77985   
20                           Puebla  101.37346  100.71682   98.50321   
21                        Querétaro  104.51635  103.32476  102.97257   
22                     Quintana Roo  103.18851  104.09945  103.24802   
23                  San Luis Potosí   99.37760   99.05002   97.66198   
24                          Sinaloa   96.50663   96.17717   97.09227   
25                           Sonora   96.42384   95.14754   95.56714   
26                          Tabasco   97.72699   99.24818   96.29956   
27                       Tamaulipas   93.05967   94.56072   93.35393   
28                         Tlaxcala  100.77689  102.54729  101.28561   
29  Veracruz de Ignacio de la Llave   99.11994   99.12267   95.87129   
30                          Yucatán  101.89037   97.61515  100.58461   
31                        Zacatecas   98.69542   96.48246   95.55813   

         2018       2019       2020       2021  
0    97.48356   98.09545  100.23181   98.33755  
1    98.01292   98.76864  100.17642   99.27973  
2   101.19988  101.44480  100.89693  100.91770  
3    92.90948   92.72780   94.99509   94.89013  
4    97.32727   97.75960   98.07359   99.20941  
5    91.93321   93.91699   95.10276   92.44448  
6    92.83203   92.61559   94.33084   97.04795  
7    97.61851   99.30733  100.06265   98.30975  
8    94.05605   93.73268   94.42753   90.76606  
9    95.17021   95.17954   96.66245   94.46514  
10   96.65978   97.29179   97.37805   96.88783  
11   91.53002   89.39594   91.91862   92.79148  
12  101.10369  101.48433  101.36374  100.96689  
13   95.26851   94.83041   96.90785   95.94899  
14   97.13723   96.84956   96.48052   95.12438  
15   89.70445   89.06785   89.23151   89.85112  
16   94.27973   94.96889   95.15927   94.00181  
17   97.29402   99.26859   98.65876   99.14953  
18  101.94159  102.23368  102.95628  102.06407  
19   98.48485   95.40324   92.68589   92.15127  
20   97.89739   97.70748   98.06503   96.93452  
21  101.80708  103.44124  103.13082  101.61135  
22  103.91528  102.70135  103.13903   98.94885  
23   96.65435   96.83686   98.50864   97.84934  
24   96.36443   96.75575   97.83566   98.61268  
25   95.05421   96.49885   97.55233   97.08505  
26   95.48089   94.17452   95.72093   96.54894  
27   95.60629   95.11055   96.95658   96.38036  
28  100.60201   99.91801  100.20492   98.73575  
29   92.88161   92.64212   93.90028   94.35480  
30   97.25829   97.69962   98.92196   98.66198  
31   95.36640   96.27202   97.47967   96.75270

In [46]:
df_efic['2022'] = df_efic.iloc[:,-7:].mean(axis=1)
df_efic['2023'] = df_efic.iloc[:,-7:].mean(axis=1)

In [47]:
df_efic.sort_values('Entidad federativa', inplace=True)
df_efic.insert(1, 'Clave_Ent', list(range(1, 33)))

In [48]:
df_efic

Entidad federativa  Clave_Ent       2015       2016  \
0                    Aguascalientes          1   99.48262   99.35626   
1                   Baja California          2   98.14218   98.66109   
2               Baja California Sur          3  100.85804  100.22020   
3                          Campeche          4   97.12600   95.57463   
6                           Chiapas          5   95.16524   94.79580   
7                         Chihuahua          6   97.12574   99.88062   
8                  Ciudad de México          7   98.97006   96.48690   
4              Coahuila de Zaragoza          8   98.00489   98.33659   
5                            Colima          9  104.72692   98.76622   
9                           Durango         10   98.18177   96.03335   
10                       Guanajuato         11   98.85114   96.92807   
11                         Guerrero         12   97.02454   97.46167   
12                          Hidalgo         13  102.89174  102.91048   
13                          Jalisco         14   96.40105   95.46034   
15              Michoacán de Ocampo         15   94.29299   95.71484   
16                          Morelos         16   96.52155   95.99525   
14                           México         17   99.41544   99.41464   
17                          Nayarit         18  100.89731   99.37761   
18                       Nuevo León         19  101.67270  103.10297   
19                           Oaxaca         20   91.30149   88.39060   
20                           Puebla         21  101.37346  100.71682   
21                        Querétaro         22  104.51635  103.32476   
22                     Quintana Roo         23  103.18851  104.09945   
23                  San Luis Potosí         24   99.37760   99.05002   
24                          Sinaloa         25   96.50663   96.17717   
25                           Sonora         26   96.42384   95.14754   
26                          Tabasco         27   97.72699   99.24818   
27                       Tamaulipas         28   93.05967   94.56072   
28                         Tlaxcala         29  100.77689  102.54729   
29  Veracruz de Ignacio de la Llave         30   99.11994   99.12267   
30                          Yucatán         31  101.89037   97.61515   
31                        Zacatecas         32   98.69542   96.48246   

         2017       2018       2019       2020       2021        2022  \
0   100.07392   97.48356   98.09545  100.23181   98.33755   99.008739   
1    97.24271   98.01292   98.76864  100.17642   99.27973   98.611956   
2   101.06473  101.19988  101.44480  100.89693  100.91770  100.943183   
3    95.45344   92.90948   92.72780   94.99509   94.89013   94.810939   
6    94.79650   92.83203   92.61559   94.33084   97.04795   94.511993   
7    97.52694   97.61851   99.30733  100.06265   98.30975   98.547363   
8    97.40903   94.05605   93.73268   94.42753   90.76606   95.121187   
4    99.06695   97.32727   97.75960   98.07359   99.20941   98.254043   
5    97.61600   91.93321   93.91699   95.10276   92.44448   96.358083   
9    95.33467   95.17021   95.17954   96.66245   94.46514   95.861019   
10   96.81603   96.65978   97.29179   97.37805   96.88783   97.258956   
11   93.85728   91.53002   89.39594   91.91862   92.79148   93.425650   
12  101.53272  101.10369  101.48433  101.36374  100.96689  101.750513   
13   96.37977   95.26851   94.83041   96.90785   95.94899   95.885274   
15   95.53016   89.70445   89.06785   89.23151   89.85112   91.913274   
16   95.84663   94.27973   94.96889   95.15927   94.00181   95.253304   
14   98.47468   97.13723   96.84956   96.48052   95.12438   97.556636   
17   99.21260   97.29402   99.26859   98.65876   99.14953   99.122631   
18  102.89772  101.94159  102.23368  102.95628  102.06407  102.409859   
19   96.77985   98.48485   95.40324   92.68589   92.15127   93.599599   
20   98.50321   97.89739   97.70748   98.06503   96.93452   98.742559   
21  102.97257  101.80708  103.4412

In [49]:
df_efic = df_efic.loc[:,'2015':].stack()

In [50]:
df_efic = df_efic.reset_index()
df_efic = df_efic.rename(columns={'level_0': 'Clave_Ent', 'level_1': 'Año', 0: 'EficienciaPrimaria'})
df_efic['Clave_Ent'] += 1

In [51]:
df_efic

Clave_Ent   Año  EficienciaPrimaria
0            1  2015           99.482620
1            1  2016           99.356260
2            1  2017          100.073920
3            1  2018           97.483560
4            1  2019           98.095450
..         ...   ...                 ...
283         32  2019           96.272020
284         32  2020           97.479670
285         32  2021           96.752700
286         32  2022           96.658114
287         32  2023           96.367071

[288 rows x 3 columns]

In [52]:
df_efic['Año'] = df_efic['Año'].astype(int)

In [53]:
df = pd.merge(df, df_efic, on=['Clave_Ent', 'Año'], how='inner')

In [54]:
df

Año  Clave_Ent         Entidad  \
0      2015          1  Aguascalientes   
1      2015          1  Aguascalientes   
2      2015          1  Aguascalientes   
3      2015          1  Aguascalientes   
4      2015          1  Aguascalientes   
...     ...        ...             ...   
11515  2023         32       Zacatecas   
11516  2023         32       Zacatecas   
11517  2023         32       Zacatecas   
11518  2023         32       Zacatecas   
11519  2023         32       Zacatecas   

                                          Tipo de delito  Total_delitos  \
0                                                 Aborto            5.0   
1                                     Abuso de confianza          419.0   
2                                           Abuso sexual           18.0   
3                                           Acoso sexual            0.0   
4                                 Allanamiento de morada          169.0   
...                                                  ...            ...   
11515                                 Tráfico de menores            0.0   
11516                               Violación equiparada          129.0   
11517                                   Violación simple          161.0   
11518  Violencia de género en todas sus modalidades d...            0.0   
11519                                 Violencia familiar         3674.0   

       Poblacion       PIB Desocupacion  EficienciaPrimaria  
0      1305301.5  294497.0     4.503325           99.482620  
1      1305301.5  294497.0     4.503325           99.482620  
2      1305301.5  294497.0     4.503325           99.482620  
3      1305301.5  294497.0     4.503325           99.482620  
4      1305301.5  294497.0     4.503325           99.482620  
...          ...       ...          ...                 ...  
11515  1661579.0  218885.5     2.872008           96.367071  
11516  1661579.0  218885.5     2.872008           96.367071  
11517  1661579.0  218885.5     2.872008           96.367071  
11518  1661579.0  218885.5     2.872008           96.367071  
11519  1661579.0  218885.5     2.872008           96.367071  

[11520 rows x 9 columns]

### Medicos por cada cien mil habitantes

In [55]:
df_med = pd.read_csv('datos/INEGI/Medicos.csv')

In [56]:
df_med['2023'] = df_med.iloc[:,-7:].mean(axis=1)

In [57]:
df_med.sort_values('Entidad federativa', inplace=True)
df_med.insert(1, 'Clave_Ent', list(range(1, 33)))

In [58]:
df_med

Entidad federativa  Clave_Ent     2015     2016     2017  \
0                    Aguascalientes          1  1.90087  1.98550  2.16623   
1                   Baja California          2  1.58419  1.59542  1.58135   
2               Baja California Sur          3  2.33295  2.43296  2.36968   
3                          Campeche          4  2.05327  2.15508  2.14011   
6                           Chiapas          5  1.26116  1.36668  1.43907   
7                         Chihuahua          6  1.56480  1.64225  1.60839   
8                  Ciudad de México          7  3.79995  3.82686  3.87974   
4              Coahuila de Zaragoza          8  1.80359  1.79146  1.82280   
5                            Colima          9  2.30107  2.46245  2.52845   
9                           Durango         10  1.95581  1.99922  1.99266   
10                       Guanajuato         11  1.39597  1.42572  1.49258   
11                         Guerrero         12  1.69413  1.74646  1.87639   
12                          Hidalgo         13  1.53661  1.54902  1.54905   
13                          Jalisco         14  1.88179  1.87419  1.83339   
15              Michoacán de Ocampo         15  1.52840  1.52686  1.54362   
16                          Morelos         16  1.65690  1.72796  1.76491   
14                           México         17  1.27998  1.35069  1.25892   
17                          Nayarit         18  2.08958  2.08797  2.05058   
18                       Nuevo León         19  1.64862  1.66259  1.68115   
19                           Oaxaca         20  1.52273  1.61328  1.59355   
20                           Puebla         21  1.49987  1.52326  1.56479   
21                        Querétaro         22  1.48054  1.46894  1.51325   
22                     Quintana Roo         23  1.50795  1.55704  1.54800   
23                  San Luis Potosí         24  1.57206  1.65636  1.65219   
24                          Sinaloa         25  1.84562  1.99589  2.12757   
25                           Sonora         26  2.05949  2.01759  2.20382   
26                          Tabasco         27  2.05246  2.09078  2.17334   
27                       Tamaulipas         28  2.02048  1.99739  2.04484   
28                         Tlaxcala         29  1.75712  1.77073  1.76215   
29  Veracruz de Ignacio de la Llave         30  1.55331  1.56973  1.59097   
30                          Yucatán         31  2.06572  2.14858  2.17780   
31                        Zacatecas         32  1.85418  1.85795  1.88287   

       2018     2019     2020     2021     2022      2023  
0   2.06086  2.15200  2.13729  2.20148  2.23791  2.134467  
1   1.49628  1.52373  1.55889  1.54347  1.48371  1.540407  
2   2.36669  2.44686  2.39971  2.41515  2.37040  2.400207  
3   2.49056  2.40656  2.42233  2.33093  2.38935  2.333560  
6   1.40410  1.31228  1.35059  1.37342  1.41995  1.380870  
7   1.73341  1.70000  1.66788  1.86558  1.84979  1.723900  
8   3.82702  3.86971  3.88584  4.01439  4.19122  3.927826  
4   1.85342  1.91401  1.87481  1.92183  1.93606  1.873484  
5   2.63593  2.67699  2.70962  2.66733  2.75043  2.633029  
9   2.03489  2.01319  2.02728  2.21261  2.15307  2.061846  
10  1.50044  1.53511  1.56708  1.61310  1.62181  1.536549  
11  1.97026  1.92342  1.89725  1.97925  1.96086  1.907699  
12  1.56768  1.55696  1.67946  1.71852  1.75781  1.625500  
13  1.79338  1.75369  1.75818  1.80849  1.89327  1.816370  
15  1.55576  1.52844  1.61854  1.63267  1.63134  1.576747  
16  1.76025  1.72914  1.67070  1.65963  1.68610  1.714099  
14  1.28398  1.33156  1.35588  1.39598  1.40739  1.340629  
17  2.17713  2.20403  2.45472  2.58749  2.54965  2.301653  
18  1.81328  1.79701  1.75365  1.80760  1.85153  1.766687  
19  1.58984  1.54250  1.57191  1.59239  1.70454  1.601144  
20  1.48933  1.52898  1.44007  1.52738  1.59815  1.524566  
21  1.49326  1.66960  1.66583  1.82809  1.77975  1.631246  
22  1.44987  1.45156  1.40182  1.39257  1.40909  1.458564  
23  1.62061  1.54076  1.58478  1.61

In [59]:
df_med = df_med.loc[:,'2015':].stack()

In [60]:
df_med = df_med.reset_index()
df_med = df_med.rename(columns={'level_0': 'Clave_Ent', 'level_1': 'Año', 0: 'Medicos'})
df_med['Clave_Ent'] += 1

In [61]:
df_med

Clave_Ent   Año   Medicos
0            1  2015  1.900870
1            1  2016  1.985500
2            1  2017  2.166230
3            1  2018  2.060860
4            1  2019  2.152000
..         ...   ...       ...
283         32  2019  1.921370
284         32  2020  1.917990
285         32  2021  2.000120
286         32  2022  2.011310
287         32  2023  1.932931

[288 rows x 3 columns]

In [62]:
df_med['Año'] = df_med['Año'].astype(int)

In [63]:
df = pd.merge(df, df_med, on=['Clave_Ent', 'Año'], how='inner')

In [64]:
df

Año  Clave_Ent         Entidad  \
0      2015          1  Aguascalientes   
1      2015          1  Aguascalientes   
2      2015          1  Aguascalientes   
3      2015          1  Aguascalientes   
4      2015          1  Aguascalientes   
...     ...        ...             ...   
11515  2023         32       Zacatecas   
11516  2023         32       Zacatecas   
11517  2023         32       Zacatecas   
11518  2023         32       Zacatecas   
11519  2023         32       Zacatecas   

                                          Tipo de delito  Total_delitos  \
0                                                 Aborto            5.0   
1                                     Abuso de confianza          419.0   
2                                           Abuso sexual           18.0   
3                                           Acoso sexual            0.0   
4                                 Allanamiento de morada          169.0   
...                                                  ...            ...   
11515                                 Tráfico de menores            0.0   
11516                               Violación equiparada          129.0   
11517                                   Violación simple          161.0   
11518  Violencia de género en todas sus modalidades d...            0.0   
11519                                 Violencia familiar         3674.0   

       Poblacion       PIB Desocupacion  EficienciaPrimaria   Medicos  
0      1305301.5  294497.0     4.503325           99.482620  1.900870  
1      1305301.5  294497.0     4.503325           99.482620  1.900870  
2      1305301.5  294497.0     4.503325           99.482620  1.900870  
3      1305301.5  294497.0     4.503325           99.482620  1.900870  
4      1305301.5  294497.0     4.503325           99.482620  1.900870  
...          ...       ...          ...                 ...       ...  
11515  1661579.0  218885.5     2.872008           96.367071  1.932931  
11516  1661579.0  218885.5     2.872008           96.367071  1.932931  
11517  1661579.0  218885.5     2.872008           96.367071  1.932931  
11518  1661579.0  218885.5     2.872008           96.367071  1.932931  
11519  1661579.0  218885.5     2.872008           96.367071  1.932931  

[11520 rows x 10 columns]

# Aplicando algunos modelos de ML

## Solo homicidios

In [65]:
df_homicidios = df[df['Tipo de delito'] == 'Homicidio']

In [66]:
df_homicidios

Año  Clave_Ent                          Entidad Tipo de delito  \
18     2015          1                   Aguascalientes      Homicidio   
58     2015          2                  Baja California      Homicidio   
98     2015          3              Baja California Sur      Homicidio   
138    2015          4                         Campeche      Homicidio   
178    2015          5             Coahuila de Zaragoza      Homicidio   
...     ...        ...                              ...            ...   
11338  2023         28                       Tamaulipas      Homicidio   
11378  2023         29                         Tlaxcala      Homicidio   
11418  2023         30  Veracruz de Ignacio de la Llave      Homicidio   
11458  2023         31                          Yucatán      Homicidio   
11498  2023         32                        Zacatecas      Homicidio   

       Total_delitos  Poblacion          PIB Desocupacion  EficienciaPrimaria  \
18             211.0  1305301.5   294497.000     4.503325           99.482620   
58            1219.0  3462045.0   795081.000      4.16816           98.142180   
98             201.0   717736.5   156072.000     4.786112          100.858040   
138            118.0   875402.0   700311.000     2.884725           97.126000   
178            535.0  2947581.0   897702.000     5.101025           98.004890   
...              ...        ...          ...          ...                 ...   
11338         1112.0  3605489.3   722614.000     3.124213           95.281778   
11378          141.0  1394889.3   141448.750     3.335152          100.553584   
11418         1814.0  8188394.5  1035069.875     2.108605           94.883716   
11458          165.0  2430494.3   350027.375     1.848492           98.527005   
11498         1050.0  1661579.0   218885.500     2.872008           96.367071   

        Medicos  
18     1.900870  
58     1.584190  
98     2.332950  
138    2.053270  
178    1.803590  
...         ...  
11338  2.016107  
11378  1.765706  
11418  1.621420  
11458  2.253207  
11498  1.932931  

[288 rows x 10 columns]

In [67]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [68]:
X = df_homicidios.drop(['Clave_Ent', 'Año', 'Entidad','Tipo de delito', 'Total_delitos'], axis = 1)

In [69]:
y = df_homicidios['Total_delitos']

In [70]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size = 0.8)

In [71]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((230, 5), (58, 5), (230,), (58,))

### Regresion Lineal

In [72]:
from sklearn.linear_model import LinearRegression
LinearRegression = LinearRegression()

In [73]:
model_linear_regression = Pipeline([
    ('scaler', StandardScaler()),   # Step 1: Scale the features
    ('regression', LinearRegression)  # Step 2: Fit linear regression model
])

In [74]:
model_linear_regression.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('regression', LinearRegression())])

In [75]:
muestra_datos = X_test.iloc[:5]

model_linear_regression.predict(muestra_datos)

array([1832.05013721, 2061.76809698, 1004.44142727,  821.87887907,
        592.8332687 ])

In [76]:
list(y_test.iloc[:5])

[1873.0, 1466.0, 1421.0, 1228.0, 1001.0]

In [77]:
from sklearn.model_selection import cross_val_score

linear_scores = cross_val_score(model_linear_regression, X, y,
                               scoring = 'neg_mean_squared_error', cv =5)

linear_scores

array([-357483.94134195, -391533.30829133, -589698.59748333,
       -360209.34249044, -294328.7603252 ])

In [78]:
linear_rmse_scores = np.sqrt(-linear_scores)
linear_rmse_scores

array([597.89960808, 625.72622471, 767.9183534 , 600.17442672,
       542.52074645])

In [79]:
def display_scores(scores):
    print('Scores:', scores)
    print('Mean:', scores.mean())
    print('Standard Dev:', scores.std())

In [80]:
display_scores(linear_rmse_scores)

Scores: [597.89960808 625.72622471 767.9183534  600.17442672 542.52074645]
Mean: 626.8478718711676
Standard Dev: 75.58131724863333


### DecisionTree

In [81]:
#Aplicar el modelo de arboles de decision con DecisionTreeRegressor
from sklearn.tree import DecisionTreeRegressor

#1. Nombrar una variable para nuestro modelo
tree_reg = DecisionTreeRegressor(random_state=42)

In [82]:
#2. Definir el Pipeline : Transformación  + modelo
model_tree_reg = Pipeline(steps = [
    ('scaler', StandardScaler()),
    ('tree_reg', tree_reg)
])

In [83]:
#3. Ajustar el modelo
model_tree_reg.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('tree_reg', DecisionTreeRegressor(random_state=42))])

In [84]:
#Comparar con el modelo de regresion lineal para una muestra de datos
print(model_linear_regression.predict(muestra_datos))
print(model_tree_reg.predict(muestra_datos))

[1832.05013721 2061.76809698 1004.44142727  821.87887907  592.8332687 ]
[2061. 1816. 1968.  231.  997.]


In [85]:
list(y_test.iloc[:5])

[1873.0, 1466.0, 1421.0, 1228.0, 1001.0]

In [86]:
from sklearn.model_selection import cross_val_score

tree_reg_scores = cross_val_score(model_tree_reg, X, y,
                               scoring = 'neg_mean_squared_error', cv = 5)

tree_reg_scores

array([-424561.67241379, -206708.29310345, -427914.65517241,
       -164898.98245614, -264197.14035088])

In [87]:
tree_reg_scores = np.sqrt(-tree_reg_scores)
tree_reg_scores

array([651.58397188, 454.65183724, 654.15185941, 406.07755719,
       514.00110929])

In [88]:
display_scores(tree_reg_scores)

Scores: [651.58397188 454.65183724 654.15185941 406.07755719 514.00110929]
Mean: 536.093267002964
Standard Dev: 101.2924369013957


### RandomForest

In [89]:
from sklearn.ensemble import RandomForestRegressor

In [90]:
forest_reg = RandomForestRegressor(n_estimators = 10, random_state = 42)

In [91]:
model_forest_reg = Pipeline(steps = [
    ('scaler', StandardScaler()),
    ('forest_reg', forest_reg)
])

In [92]:
model_forest_reg.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('forest_reg',
                 RandomForestRegressor(n_estimators=10, random_state=42))])

In [93]:
#Comparar con el modelo de regresion lineal para una muestra de datos
print(model_linear_regression.predict(muestra_datos))
print(model_forest_reg.predict(muestra_datos))
print(model_tree_reg.predict(muestra_datos))

[1832.05013721 2061.76809698 1004.44142727  821.87887907  592.8332687 ]
[2054.2 1828.8 1500.6  747.2  961.6]
[2061. 1816. 1968.  231.  997.]


In [94]:
#Comparamos con los valores reales
list(y_test.iloc[:5])

[1873.0, 1466.0, 1421.0, 1228.0, 1001.0]

In [95]:
from sklearn.model_selection import cross_val_score

forest_reg_scores = cross_val_score(model_forest_reg, X, y,
                               scoring = 'neg_mean_squared_error', cv = 5)

forest_reg_scores

array([-446738.42465517, -150980.80396552, -271018.41      ,
       -126954.70631579, -131850.12982456])

In [96]:
forest_reg_scores = np.sqrt(-forest_reg_scores)
forest_reg_scores

array([668.38493748, 388.56248399, 520.59428541, 356.30703939,
       363.11173187])

In [97]:
display_scores(forest_reg_scores)

Scores: [668.38493748 388.56248399 520.59428541 356.30703939 363.11173187]
Mean: 459.3920956286655
Standard Dev: 120.2804947866077


## Utilizando todos los datos

In [98]:
df

Año  Clave_Ent         Entidad  \
0      2015          1  Aguascalientes   
1      2015          1  Aguascalientes   
2      2015          1  Aguascalientes   
3      2015          1  Aguascalientes   
4      2015          1  Aguascalientes   
...     ...        ...             ...   
11515  2023         32       Zacatecas   
11516  2023         32       Zacatecas   
11517  2023         32       Zacatecas   
11518  2023         32       Zacatecas   
11519  2023         32       Zacatecas   

                                          Tipo de delito  Total_delitos  \
0                                                 Aborto            5.0   
1                                     Abuso de confianza          419.0   
2                                           Abuso sexual           18.0   
3                                           Acoso sexual            0.0   
4                                 Allanamiento de morada          169.0   
...                                                  ...            ...   
11515                                 Tráfico de menores            0.0   
11516                               Violación equiparada          129.0   
11517                                   Violación simple          161.0   
11518  Violencia de género en todas sus modalidades d...            0.0   
11519                                 Violencia familiar         3674.0   

       Poblacion       PIB Desocupacion  EficienciaPrimaria   Medicos  
0      1305301.5  294497.0     4.503325           99.482620  1.900870  
1      1305301.5  294497.0     4.503325           99.482620  1.900870  
2      1305301.5  294497.0     4.503325           99.482620  1.900870  
3      1305301.5  294497.0     4.503325           99.482620  1.900870  
4      1305301.5  294497.0     4.503325           99.482620  1.900870  
...          ...       ...          ...                 ...       ...  
11515  1661579.0  218885.5     2.872008           96.367071  1.932931  
11516  1661579.0  218885.5     2.872008           96.367071  1.932931  
11517  1661579.0  218885.5     2.872008           96.367071  1.932931  
11518  1661579.0  218885.5     2.872008           96.367071  1.932931  
11519  1661579.0  218885.5     2.872008           96.367071  1.932931  

[11520 rows x 10 columns]

In [99]:
numeric_list = ['Poblacion', 'PIB','Desocupacion','EficienciaPrimaria', 'Medicos']
categorical_list = ['Tipo de delito']

In [100]:
numeric_transformer = Pipeline( steps = [ ( 'Scaler', StandardScaler() ) ] )
categorical_transformer = Pipeline( steps = [ ( 'onehot', OneHotEncoder() ) ] )

In [101]:
transformer = ColumnTransformer([
    ('num', numeric_transformer, numeric_list), ('cat', categorical_transformer, categorical_list)
])

In [102]:
X = df.drop(['Total_delitos', 'Año', 'Entidad','Clave_Ent'], axis = 1)

In [103]:
y = df['Total_delitos']

In [104]:
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size = 0.85)

In [105]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((9792, 6), (1728, 6), (9792,), (1728,))

### Regresion Lineal

In [106]:
from sklearn.linear_model import LinearRegression
linear_regression = LinearRegression()

In [107]:
model_linear_regression2 = Pipeline([
    ('tranformer', transformer), ('linear_regression', linear_regression)
])

In [108]:
model_linear_regression2.fit(X_train, y_train)

Pipeline(steps=[('tranformer',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('Scaler',
                                                                   StandardScaler())]),
                                                  ['Poblacion', 'PIB',
                                                   'Desocupacion',
                                                   'EficienciaPrimaria',
                                                   'Medicos']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder())]),
                                                  ['Tipo de delito'])])),
                ('linear_regression', LinearRegression())])

In [109]:
muestra_datos = X_test.iloc[:5]

model_linear_regression2.predict(muestra_datos)

array([ -318.12701476,    79.95188995, -1200.27987468,  4414.57842882,
       -1212.52053693])

In [110]:
list(y_test.iloc[:5])

[42.0, 829.0, 0.0, 532.0, 465.0]

In [111]:
from sklearn.model_selection import cross_val_score

linear_scores = cross_val_score(model_linear_regression2, X, y,
                               scoring = 'neg_mean_squared_error', cv =5)

linear_scores

array([-28952907.77195829, -37748214.81112184, -21386823.16564592,
       -25016421.71028467, -26560054.7945392 ])

In [112]:
linear_rmse_scores = np.sqrt(-linear_scores)
linear_rmse_scores

array([5380.79062703, 6143.95758539, 4624.58897262, 5001.64190144,
       5153.64480679])

In [113]:
display_scores(linear_rmse_scores)

Scores: [5380.79062703 6143.95758539 4624.58897262 5001.64190144 5153.64480679]
Mean: 5260.924778655179
Standard Dev: 505.52440499142983


### DecisionTree

In [114]:
tree_reg = DecisionTreeRegressor(random_state=42)

In [115]:
model_tree_reg2 = Pipeline(steps = [
    ('tranformer', transformer),
    ('tree_reg', tree_reg)
])

In [116]:
model_tree_reg2.fit(X_train, y_train)

Pipeline(steps=[('tranformer',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('Scaler',
                                                                   StandardScaler())]),
                                                  ['Poblacion', 'PIB',
                                                   'Desocupacion',
                                                   'EficienciaPrimaria',
                                                   'Medicos']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder())]),
                                                  ['Tipo de delito'])])),
                ('tree_reg', DecisionTreeRegressor(random_state=42))])

In [117]:
print(model_linear_regression2.predict(muestra_datos))
print(model_tree_reg2.predict(muestra_datos))

[ -318.12701476    79.95188995 -1200.27987468  4414.57842882
 -1212.52053693]
[  1. 879.   3. 344.  35.]


In [118]:
list(y_test.iloc[:5])

[42.0, 829.0, 0.0, 532.0, 465.0]

In [119]:
from sklearn.model_selection import cross_val_score

tree_reg_scores = cross_val_score(model_tree_reg2, X, y,
                               scoring = 'neg_mean_squared_error', cv = 5)

tree_reg_scores

array([-8147908.23046875, -2743960.96918403, -2111280.65625   ,
       -1938337.52777778, -5172550.37413194])

In [120]:
tree_reg_scores = np.sqrt(-tree_reg_scores)
tree_reg_scores

array([2854.45410376, 1656.49055813, 1453.02465783, 1392.24190706,
       2274.32415766])

In [121]:
display_scores(tree_reg_scores)

Scores: [2854.45410376 1656.49055813 1453.02465783 1392.24190706 2274.32415766]
Mean: 1926.1070768886389
Standard Dev: 559.3917052674294


### Random Forest

In [122]:
forest_reg = RandomForestRegressor(n_estimators = 10, random_state = 42)

In [123]:
model_forest_reg2 = Pipeline(steps = [
    ('tranformer', transformer),
    ('forest_reg', forest_reg)
])

In [124]:
model_forest_reg2.fit(X_train, y_train)

Pipeline(steps=[('tranformer',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('Scaler',
                                                                   StandardScaler())]),
                                                  ['Poblacion', 'PIB',
                                                   'Desocupacion',
                                                   'EficienciaPrimaria',
                                                   'Medicos']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder())]),
                                                  ['Tipo de delito'])])),
                ('forest_reg',
                 RandomForestRegressor(n_estimators=10, random_state=42))])

In [125]:
print(model_linear_regression2.predict(muestra_datos))
print(model_tree_reg2.predict(muestra_datos))
print(model_forest_reg2.predict(muestra_datos))


[ -318.12701476    79.95188995 -1200.27987468  4414.57842882
 -1212.52053693]
[  1. 879.   3. 344.  35.]
[  5.9 781.6   3.9 377.  216.9]


In [126]:
list(y_test.iloc[:5])

[42.0, 829.0, 0.0, 532.0, 465.0]

In [127]:
from sklearn.model_selection import cross_val_score

forest_reg_scores = cross_val_score(model_forest_reg2, X, y,
                               scoring = 'neg_mean_squared_error', cv = 5)

forest_reg_scores

array([-3775157.14891927, -3408703.21687934, -1388713.38810764,
        -972034.68722656, -4358570.39980903])

In [128]:
forest_reg_scores = np.sqrt(-forest_reg_scores)
forest_reg_scores

array([1942.97636345, 1846.26737416, 1178.43684095,  985.918195  ,
       2087.71894656])

In [129]:
display_scores(forest_reg_scores)

Scores: [1942.97636345 1846.26737416 1178.43684095  985.918195   2087.71894656]
Mean: 1608.2635440218346
Standard Dev: 440.59521236470164
